name = "card-trooper"
compatibility_date = "2025-09-27"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
main = "./dist/_worker.js"

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "card-trooper"
database_id = "a13bca15-9861-4892-8487-d33680601be2"
